---

- name: Setup node 0.12
  raw: curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
  sudo: yes

- name: Install the nodejs and npm packages (APT)
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ nodejs_apt_cache_valid_time }}
  with_items: nodejs_apt_packages
  environment: env
  when: ansible_os_family == "Debian"
  tags: [packages,nodejs]

- name: Install global npm packages
  npm: name={{ item }} global=yes
  with_items: nodejs_packages_global
  tags: [packages,npm]